context:
  name: deepsearch-toolkit
  version: 1.1.1
  python_min: "3.9" # remove this line once https://github.com/prefix-dev/rattler-build/pull/1122 is available

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/deepsearch_toolkit-${{ version }}.tar.gz
  sha256: 0777d26b80ae97f773d2c832288cadcfcb874ca1cf11b8284f03a25c8dd013e0

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - deepsearch = deepsearch.cli:app

requirements:
  host:
    - python ${{ python_min }}
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - urllib3 >=1.26.8
    - six >=1.16.0
    - certifi >=2024.07.04
    - python-dateutil >=2.8.2
    - pydantic >=2.0.3
    - pydantic-settings >=2.4.0
    - python-dotenv >=1.0.0
    - requests >=2.27.1
    - typer >=0.9.0
    - platformdirs >=3.5.1
    - tabulate >=0.8.9
    - pluggy >=1.0.0
    - tqdm >=4.64.0
    - docling-core >=2.0.0

tests:
  - python:
      imports:
        - deepsearch
      pip_check: false
  - script:
      - deepsearch --help

about:
  summary: Interact with the Deep Search platform for new knowledge explorations and discoveries
  license_file: LICENSE
  license: MIT
  homepage: https://ds4sd.github.io/deepsearch-toolkit/

extra:
  recipe-maintainers:
    - hadim
